name : nslg
dependencies:
  - python=3.7
  - pip
  - pip:
      - numpy
      - torch
      - torchtext
      - tensorboardX
      - tqdm
      - nltk
      - ansicolors
      - torch_optimizer
      - tensorboard
      - pandas
      - scipy
      - sklearn
      - matplotlib
      - seaborn
      - adjustText

